license:
  main: Apache-2.0
  additional: 
    - MIT
  report_invalid: true
  report_unknown: true
  report_missing: true
copyright:
  check: true
exclude:
  extensions:
    - yml
    - yaml
    - html
    - rst
    - conf
    - cfg
    - config
    - bat
    - md
  special_file:
    - SConscript
    - SConstruct
    - ChangeLog
    - Kconfig
    - rtconfig.h
    - config.h
    - rtconfig.py
  langs:
    - HTML
extensions:
  - path:
      "external/ffmpeg"
    license:
      - LGPL-2.1-only
      - LGPL-2.1-or-later
      - LGPL-3.0-only
      - LGPL-3.0-or-later
  - path:
      "external/faad2"
    license:
      - GPL-2.0-only
      - GPL-2.0-or-later